openedx/edx-repo-health

repo_health/check_travis_yml.py

Depending on how travis.yml is written, python info is parsed differently
Moving forward, we should find a less brittle way to find python info,
or have stronger standards for travis.yml files

Modified fixture to be more versitile

---

repo_health_dashboard/configuration.yaml
repo_health_dashboard/repo_health_dashboard.py

repo-health-data contains alot of old data(from repos that are deleted or renamed). This old data is adding alot of noise to our final csv output. So adding this data lifetime check to make sure old files are ignored.

Adding timestamp check for data processing

---

docs/check_function.rst
repo_health/check_github.py

Added checks for all the information of interest that could easily be obtained from the `github.py` package, and put in a little extra effort to get the byte count for each programming language (which `github.py` hasn't implemented yet).  Also fixed some reST formatting in the docs.
Example output from the new checks for this repo itself:
```yaml
github:
allows_merge_commit: true
allows_rebase_merge: true
allows_squash_merge: true
code_of_conduct: null
created_at: 2020-03-24 13:36:50
default_branch: master
description: ''
disk_usage_kb: 110
fork_count: 3
has_issues: true
has_wiki: true
is_archived: false
is_disabled: false
is_fork: false
is_locked: false
is_private: false
last_push: 2020-07-17 06:30:26
license: Apache License 2.0
language_bytes:
css: 0
dockerfile: 0
go: 0
groovy: 0
html: …
```

Add initial checks for data from the GitHub API ARCHBOM-1310

---

repo_health/check_github.py

Don't choke on repositories which haven't specified a license or a default branch.

Handle missing license or default branch ARCHBOM-1310

---

repo_health/check_github.py

Get around the issue fetching data from GitHub for edx-blog (and any similar problems that may crop up later in the repo health dashboard job).  I'd like to enhance this later to have the fixture report the exact problem encountered without blowing up the test suite, but for now I just want to get the new data in the dashboard for most of our repos.

Skip GitHub API checks when the data can't be fetched ARCHBOM-1310

---

.travis.yml
setup.py
tox.ini

Allows us to upgrade some dependencies and avoid confusion regarding the appropriate aiohttp version (recent versions only support Python 3.5.3 and above).

Drop Python 3.5 support

---

repo_health/check_ownership.py
requirements/base.in
requirements/base.txt
requirements/dev.txt
requirements/doc.txt
requirements/pip-tools.txt
requirements/quality.txt
requirements/test.txt
requirements/travis.txt

Added a new check to get repository ownership data from the master spreadsheet, and added `gspread` as a dependency.  The new check should be skipped unless the appropriate environment variables are set (which will only be true for the Jenkins job and some local dev environments).
It looks like some of the requirements files (like `travis.txt`) have too much in them, but I'll ticket fixing that separately.

Add ownership checks ARCHBOM-1383

---

repo_health/check_github.py
requirements/dev.txt
requirements/doc.txt
requirements/quality.txt
requirements/test.in
requirements/test.txt
requirements/travis.in
requirements/travis.txt
tox.ini

Disable the code of conduct GitHub check, since that breaks in github.py 0.5.0 if one is actually present (I think that's fixed on master).  Also refactored the requirements files a little to avoid including dependencies in contexts where they aren't needed.  Finally, updated `tox.ini` to avoid using a deprecated setting name.

Disable code of conduct check, refactor dependencies ARCHBOM-1383

---

repo_health/check_github.py
repo_health/check_openedx_yaml.py
repo_health_dashboard/configuration.yaml
requirements/base.in
requirements/base.txt
requirements/dev.txt
requirements/doc.txt
requirements/github.in
requirements/quality.txt
requirements/test.txt

This should get the updated repo health dashboard fully working again:
* Upgrades `github.py` to fix code of conduct processing
* Upgrades `pytest-repo-health` to facilitate the above upgrade and fix handling of repos with a period in their name
* Removes the openedx.yaml owner check, replaces it in the dashboard config with the squad data from the ownership spreadsheet
* Streamlines checks for compliance with specific OEPs

Finish ownership and code of conduct fixes ARCHBOM-1383

---

requirements/base.txt
requirements/constraints.txt
requirements/dev.txt
requirements/doc.txt
requirements/quality.txt
requirements/test.txt
requirements/travis.txt

- Pinned `importlib-metadata==1.7.0` as `version>1.7.0` is causing conflicts for python36 in running `make upgrade`.

Pin importlib-metadata to 1.7.0 for python36

---

requirements/base.txt
requirements/constraints.txt
requirements/dev.txt
requirements/doc.txt
requirements/quality.txt
requirements/test.txt
requirements/travis.txt

- `importlib-metadata<2.0.0` was causing conflicts in running `make upgrade` with `python3.6`.
- Unpinned `importlib-metadata` constraint after fixing the issue in https://github.com/pypa/virtualenv/pull/1953 and https://github.com/tox-dev/tox/pull/1682.

Unpinned importlib-metadata constraint

---

repo_health/check_travis_integration.py

https://openedx.atlassian.net/browse/BOM-1980
Adding a check to see if the repo is integrated with travis-ci.org or .com
For ecom it is showing
```
travis_ci:
active_on_com: true
active_on_org: false
```
For registrar 
```
travis_ci:
active_on_com: false
active_on_org: true
```

check if a repo containing a .travis.yml file is using travis-ci.org, travis-ci.com, or neither.

---

requirements/base.txt
requirements/dev.txt
requirements/doc.txt
requirements/quality.txt
requirements/test.txt

version still needs to be merged: https://github.com/edx/pytest-repo-health/pull/58

ARCHBOM-1475: updating pytest-repo-health to new version

---

repo_health/check_travis_integration.py

travis.org api is not giving correct result. It might be due to the rate/limit api. 
Adding some logging.

Adding logging for travis.org api status checking.

---

repo_health/check_travis_integration.py

Added regex for url extraction. On jenkins its using https but locally it was using ssh link.

updated the travis CI migration check to use regex for repo extraction

---

repo_health/check_dependencies.py
repo_health/check_existence.py
repo_health/check_requirements.py

**Issue:** [BOM-1977](https://openedx.atlassian.net/browse/BOM-1977)
- Check if the `requirements` folder exists.
- Extracting all the package dependencies from the `requirements` folder. 
- Splitting the `PYPI` and `GitHub` dependencies.

Checking requirements folder existence

---

repo_health/check_dependencies.py

**Issue:** [BOM-1977](https://openedx.atlassian.net/browse/BOM-1977)
- In https://github.com/edx/edx-repo-health/pull/63, the check to fetch files recursively was missing & pypi dependencies were overwritten during the final iteration.
- Updated the `check_dependencies` script to recursively fetch all requirements. 
- Fixed the error to accumulate all the pypi packages. 
The script can be tested by running the following command:
`pytest --repo-health --repo-health-path=. --repo-path=../{Target_Repo} --noconftest`

Fixed to get dependencies from recursive folders

---

repo_health/check_travis_integration.py
requirements/dev.txt
requirements/doc.txt
requirements/quality.txt
requirements/test.in
requirements/test.txt
tests/test_travis_integration.py
tox.ini

updated the script to use **travis-ci.com** API instead of **travis-ci.org** and changes made to handle all possible cases.
the updated script has been tested with the following scenarios:
- a repo that was migrated over from **travis-ci.org** to **travis-ci.com** e.g `ecommerce`
- a repo that never used travis CI e.g `edx-platform`
- a repo that never used travis-ci.org and started out with travis-ci.com instead (no migration history) e.g `edx-cookiecutters`

updated the fixture to handle all possible cases of travis integration

---

repo_health/check_travis_yml.py

Following error came when we added forks and archived repos in `org-repo-health-report` job, so made a fix.
```
10:47:40     @pytest.fixture(name="python_versions_in_travis")
10:47:40     def fixture_python_version(parsed_data_travis):
10:47:40         """
10:47:40         The list of python versions in travis tests
10:47:40         """
10:47:40         python_versions = set()
10:47:40         if "python" in parsed_data_travis.keys():
10:47:40 >           python_versions = set(parsed_data_travis["python"])
10:47:40 E           TypeError: 'float' object is not iterable
```

BOM-2091: Cover Python version float edge case

---

requirements/base.txt
requirements/constraints.txt
requirements/dev.txt
requirements/doc.txt
requirements/pip-tools.txt
requirements/quality.txt
requirements/test.txt
requirements/travis.txt

`importlib-metadata>3.0` dropped support for `python3.5` but `Tox` and `virtualenv` require `importlib-metadata<3.0` to support `python3.5` so pinning until both packages drop support for `python3.5` & update their required `importlib-metadata` version constraint.

Pinned Importlib-metadata<3.0 because of tox and virtualenv

---

repo_health/check_github_integration.py
repo_health/check_travis_integration.py
requirements/base.txt
requirements/ci.txt
requirements/constraints.txt
requirements/dev.txt
requirements/doc.txt
requirements/pip.txt
requirements/quality.txt
requirements/test.txt

`aiohttp==3.7.3(latest release)` requires [`chardet<4.0`](https://github.com/aio-libs/aiohttp/blob/2f655a59d0daedfa2a794996c4355b576c98ecc8/setup.py#L69) which is causing conflicts in make upgrade. Pinning the version in constraints until `aiohttp==4.0.0(pre-release available right now)` is released.

Pinning chardet<4.0

---

repo_health/check_readme.py

This only checked for README.rst, and would fail if it didn't exist. In
addition to not falling over if README.rst is missing, we'd like to
check the contents of README.md (and others) if it does exist.

fix: allow for other file extensions on README files

---

MANIFEST.in
README.rst
scripts/run_checks.py
setup.py

Adding new script called scripts/run_checks to make it easier to run
the checks in this repository without knowing too much about the internals of
pytest-repo-health
This script mostly takes care of the defaults and does not allow you to change
any options from default
Assumption:
Those running this script will be using checks in the repository on some external
repository

feat: run_checks CLI

---

repo_health/check_github_integration.py
repo_health/check_travis_integration.py

The "checks description" tab of the results spreadsheet has
"g.i.t.h.u.b._.a.c.t.i.o.n.s" and "t.r.a.v.i.s._.c.i" because the
argument to add_key_to_metadata is iterated, and strings are iterable.
This fixes it.

fix: don't accidentally iterate string keys

---

repo_health/check_readme.py
tests/test_check_readme.py

In some cases, we might get DNS or other network connection error when
establishing a connection.  Set those as bad URLs as well.

fix: Be able to handle URLs that fail to connect.

---

repo_health/check_openedx_yaml.py

This adds two new checks:
- openedx_yaml.release: the name of the ref to use for Open edX
releases, if any, or empty string if not.
- openedx_yaml.release-maybe: true if the openedx.yaml file includes the
cookiecutter-generated "openedx-release: maybe: true" field.

feat: check openedx.yaml release keys

---

repo_health/check_dependencies.py
repo_health/check_github.py

refactor: converting dependencies list into json ( part 1 )
1: store lists as json rather than python repr’s
BOM-2478
Previous output into csv
```
['future==0.18.2', 'code-annotations==1.1.1', 'typing-extensions==3.7.4.3']
```
Latest output into csv
```
{"appdirs":   "1.4.4", "distlib": "0.3.1",   "filelock": "3.0.12", "packaging":   "20.8", "pluggy": "0.13.1"}
```

refactor: converting dependencies list into json.

---

repo_health/check_existence.py
repo_health/check_renovate.py
repo_health/utils.py

Adding a health check to track which repos use [renovate](https://github.com/renovatebot/renovate) for Javascript dependency management and when did renovate made last PR if it is configured.
Relevant JIRA : https://openedx.atlassian.net/browse/BOM-2457

BOM-2457 : Create repo health check for Renovate usage

---

repo_health/__init__.py
repo_health/check_docs.py
repo_health/check_readme.py

Added few checks regarding
- docs build status badge in readme file
- python version mentioned in the .readthedocs.yml
- status of the latest build for Read the Docs
- time when the latest build ran for Read the Docs
[BOM-2459](https://openedx.atlassian.net/browse/BOM-2459)

feat: adds health checks for Read the Docs build

---

tests/fake_repos/python_js_repo/requirements/development.txt

Currenty version of `django-debug-toolbar`being used has a known security vulnerability. Upgrading to version 3.2.1
Relevant JIRA : https://openedx.atlassian.net/browse/BOM-2510

BOM-2510: Upgrade django-debug-toolbar

---

repo_health/check_readme.py
tests/test_check_readme.py

We had been including trailing punctuation in URLs, so a URL at the end
of a sentence would include the period.  Now we insist that the URL end
with a word or slash.

fix: smarter URL parsing in READMEs

---

CHANGELOG.rst
repo_health/__init__.py
repo_health/check_ubuntufiles.py
requirements/base.in
requirements/base.txt
requirements/ci.txt
requirements/dev.txt
requirements/doc.txt
requirements/pip-tools.txt
requirements/pip.txt
requirements/quality.txt
requirements/test.txt
tests/fake_repos/kodegail/Dockerfile
tests/fake_repos/python_js_repo/Dockerfile-testing
tests/fake_repos/python_js_repo/apt-packages.txt
tests/fake_repos/python_repo/Dockerfile
tests/fake_repos/python_repo/requirements/ubuntu/apt-packages.txt
tests/test_ubuntu_dependencies.py

Part1:
Adding new check to get docker apt-get packages
https://openedx.atlassian.net/browse/BOM-2537
This ticket has several parts I will implement in small parts.
- apt-packages.txt in the repo, and add any lines found in them.
- look for any files named Dockerfile in the repo, and try to parse out packages installed via apt-get install or update.
`edx-platform` data.
```
docker_packages:
- DEBIAN_FRONTEND=noninteractive
- build-essential
- curl
- g++
- gcc
- git
- git-core
- language-pack-en
- libfreetype6-dev
- libmysqlclient-dev
- libssl-dev
- libxml2-dev
- libxmlsec1-dev
- libxslt1-dev
- swig
- gettext
- gfortran
- graphviz
- libffi-dev
- libfreetype6-dev
- libgeos-dev
- libgraphviz-dev
- libjpeg8-dev
- liblapack-dev
- libpng-dev
- libsqlite3-dev
- libxml2-dev
- libxmlsec1-dev
- …
```

Adding new check to get apt-get packages.

---

repo_health/check_dependencies.py
tests/test_check_dependencies.py

Excluded the column from being pushed to google sheets here https://github.com/edx/repo-health-data/pull/32, so we can revert this.
Reverts edx/edx-repo-health#170

All JS Dependencies From package-lock.json

---

repo_health/check_github.py
tests/test_check_github.py

Github is unable to accuratly determine the license of some
repositories. We'd like the data is Repo Health Dashboard to be
accurate, thus adding some hardcoded info for repositories that we know
have licenses.

feat: hardcoding in license info for some repositories

---

requirements/base.in
requirements/base.txt
requirements/test.txt

**Issue:** [BOM-2749](https://openedx.atlassian.net/browse/BOM-2749)
- Package `six` was removed with the new version of `googl-auth` in https://github.com/edx/edx-repo-health/pull/205 but we need it for `google-auth-oauthlib`. Currently the fix in the `google-auth-oauthlib` package is not out which is causing the Repo Health Jobs to fail, so adding `six` in requirements to fix that.
- The failing Repo Health Report job ran successfully with this branch to verify the change: 
https://tools-edx-jenkins.edx.org/view/All%20Jobs/job/RepoHealth/job/org-repo-health-report/567/.
- This'll be removed later on in https://openedx.atlassian.net/browse/BOM-2750 when `googl-auth-oautlib>0.4.5` is released.

BOM-2749: Add package six in requirements

---

requirements/base.in
requirements/base.txt
requirements/ci.txt
requirements/dev.txt
requirements/doc.txt
requirements/quality.in
requirements/quality.txt
requirements/test.txt

**Issue:** [BOM-2750](https://openedx.atlassian.net/browse/BOM-2750)
- Package `six` was added in the requirements due to `google-auth-oauthlib` package. Now that `google-auth-oauthlib==0.4.6` is out with the fix, removed the `six` requirement.
- Added `django` in quality requirements which is needed for `pylint-django` quality checks. Previously `edx-lint` had it in the base requirements but now the new version of `edx-lint==5.1.0` has removed it from the base dependencies so we need to install in the quality requirements.

BOM-2750: Removed six and added django in quality requirements

---

repo_health/__init__.py
setup.py

This PR makes sure that this repo follows the standard that we have set across repos in the edX organization to fetch version number from `__init__.py`. 
Also I noticed that version number was placed at two different places so picked the latest one and retained that.
For more Insights into this [ARCH-BOM_DISCUSSION](https://edx-internal.slack.com/archives/CG7FM3BLY/p1636049435194900)

Fix issues with version

---

repo_health/check_readme.py

Context: We just observed a `TooManyRedirects` failure in a repo.

fix: Broaden try clause to catch all HTTP request exceptions

---

repo_health/check_existence.py
repo_health/check_makefile.py
repo_health/check_ownership.py
repo_health/check_readme.py
repo_health/check_ubuntufiles.py
repo_health_dashboard/repo_health_dashboard.py
repo_health_dashboard/utils/utils.py

Actually enabling it -- and synchronizing the settings with the cookie
cutter and/or edx-lint -- ended up being more of a rabbit hole than I
wanted to go down today. So this just fixes most of it and leaves some
line-length and line-break-near-binary-operator reports unresolved.

chore: Fix some pycodestyle issues that weren't being checked

---

repo_health/check_github.py
repo_health/utils.py

The build durations checker was raising an exception when trying to
look up information on recent builds in a repo that hadn't yet had its
default branch created. (For reference, the JSON response looked like
this: `{'node': {'defaultBranchRef': None}}`.)
- Cancel check when default branch missing
- Cancel check when no commits on branch

fix: Don't blow up on uninitialized repo

---

requirements/base.txt
requirements/ci.txt
requirements/constraints.txt
requirements/dev.txt
requirements/doc.txt
requirements/pip.txt
requirements/quality.txt
requirements/test.txt

gspread 5.2.0 introduced a backward-incompatible change related
to a sheet with extra columns with blank headers. For details
of the bug, see https://github.com/burnash/gspread/issues/1007.
We can upgrade once the issue is resolved, or if we delete these
extra columns. Note: For edX specific ownership spreadsheet, this
sheet currently contains a pivot table that would need to be
moved elsewhere.

fix: add gspread<5.2.0 constraint

---

CHANGELOG.rst
README.rst
repo_health/check_docs.py

This adds error checking to the projects list fetching.  It also only fetches it once, since it's a constant URL.  This might reduce the flaky error we saw.

fix: check errors when fetching from ReadTheDocs

---

CHANGELOG.rst
repo_health/__init__.py
requirements/base.txt
requirements/ci.txt
requirements/constraints.txt
requirements/dev.txt
requirements/doc.txt
requirements/quality.txt
requirements/test.txt

The dependency gspread had a backward incompatibility
introduced in 5.3 which was fixed in 5.3.2, so this
removes the constraint and upgrades gspread.

chore: upgrade to gspread with fix

---

CHANGELOG.rst
repo_health/__init__.py
repo_health/check_makefile.py
tests/fake_repos/makefile_repo2/Makefile
tests/test_check_makefile.py

This check verifies that we are installing pip immediately after upgrading it.
pip should be installed after the upgrade to ensure that new pip version is compatible with installed pip-tools version.
JIRA: https://2u-internal.atlassian.net/browse/BOM-3402

feat: Added check to verify pip.txt installation

---

CHANGELOG.rst
repo_health/check_setup_py.py
tests/fake_repos/just_setup_cfg/setup.cfg
tests/fake_repos/just_setup_py/setup.py
tests/test_check_setup_py.py

I discovered that some of our Python packages don't declare the `url=` setting in setup.py.  This checks for that setting.  I also added a check for the `project_urls=` setting while I was there.

feat: add checks of url= and project_urls= in Python packaging

---

tests/test_check_github.py
tests/test_check_renovate.py

Four tests were being skipped:
```
tests/test_check_github.py::test_check_settings_license_exemption_present
tests/test_check_github.py::test_check_settings_no_license_exemption_present
tests/test_check_renovate.py::test_check_renovate_true
tests/test_check_renovate.py::test_check_renovate_false
/System/Volumes/Data/root/src/edx/src/edx-repo-health/.tox/py38/lib/python3.8/site-packages/_pytest/python.py:184: PytestUnhandledCoroutineWarning: async def functions are not natively supported and have been skipped.
You need to install a suitable plugin for your async framework, for example:
- anyio
- pytest-asyncio
- pytest-tornasync
- pytest-trio
- pytest-twisted
warnings.warn(PytestUnhandledCoroutineWarning(msg.format(nodeid)))
```
The message here says you need to install a …

test: async tests have to be marked in order to run

---

CHANGELOG.rst
repo_health/check_openedx_yaml.py
tests/fake_repos/openedx_repo3/openedx.yaml
tests/test_check_openedx_yaml.py

Note repos that indicate inclusion in Open edX but that aren't in the openedx organization.

feat: check if a repo wants to be in Open edX but isn't in openedx #338

---

scripts/repo-health-script.sh

Added the `repo-health-script` in this repo to make it accessible to the new repo health job workflow for execution. 
For further details on this change, see the discussion on the PR https://github.com/openedx/.github/pull/52.

build: add repo-health-job script

---

CHANGELOG.rst
repo_health/check_github.py
repo_health/check_github_integration.py

This probably wasn't affecting repos that had moved from edx to openedx,
but was definitely giving us bad/missing data for newer repos.
This is to address https://github.com/openedx/edx-repo-health/issues/295
There's also a separate commit to fix up the changelog's rST headers.

fix: Use org name in GitHub calls, rather than hardcoded "edx"

---

CHANGELOG.rst
repo_health/check_dependabot_alerts.py
tests/data/github_dependabot_alerts_no_links.json
tests/data/github_dependabot_alerts_with_links.json
tests/test_check_dependabot_alerts.py

For [SEG-78](https://2u-internal.atlassian.net/browse/SEG-78) to add a dependabot check for edx-repo health.
Check adds total counts of open dependabot alerts, and breaks it down into individual low, medium, high, and critical severity counts

fix: add check for dependabot alert counts

---

.github/workflows/ci.yml

JIRA:PSRE-2300
Bumps the codecov version to enable the codecov GH action. 

fix: upgrade codecode version

---

CHANGELOG.rst
requirements/base.txt
requirements/ci.in
requirements/ci.txt
requirements/dev.txt
requirements/doc.txt
requirements/pip-tools.txt
requirements/quality.txt
requirements/test.txt
tox.ini

Removes codecov as a dependency since the library is deprecated.

fix: Remove codecov dependency.

---

CHANGELOG.rst
repo_health/check_setup_py.py
tests/test_check_setup_py.py

We would like to have the repo health run not fail on data not matching our expected output, such as when there may be multiple names specified. Instead, we just want the output to display an error demonstrating that the data was not valid.

feat: Do not fail on having issues fetching PyPI names.

---

tests/fake_repos/django_pytest_requirement/requirements/docs.in

The fake repo referenced the edx-sphinx-theme which is deprecated.
We're removing the reference since it's not valuable to have and might
confuse people about whether or not the deprecated repo is still in use.

fix: Remove a reference in the test fake repo.

---

.github/workflows/upgrade-python-requirements.yml

- Enable tagging `arbi-bom` team for review on the scheduled Python Requirements Upgrade PRs to avoid missing any upgrade PRs.

build: tag arbi-bom team on upgrade requirements PRs

---

repo_health/check_renovate.py
tests/test_check_renovate.py

[Add new Renovate repo health checks.](https://github.com/openedx/wg-frontend/issues/170)
This PR updates `check_renovate` with the following functionalities:
1. Total number of currently open PRs from Renovate.
2. Creation date of oldest still-open Renovate PR.

chore: update renovate check

---

tests/fake_repos/js_repo/package.json
tests/fake_repos/python_js_repo/package.json

Part of https://github.com/openedx/axim-engineering/issues/23
This replaces the `@edx/paragon` packag to point to the `paragon` package at
the `openedx` scope(`@openedx/paragon`). Imports have been updated to use the
same locations in the new package.

chore: Update to the new version of paragon in the new scope.

---

tests/fake_repos/python_js_repo/requirements/base.txt
tests/fake_repos/python_js_repo/requirements/development.txt
tests/fake_repos/python_js_repo/requirements/testing.txt
tests/test_check_dependencies.py

In this PR i removed xblock-utils and upgraded packages.
Ticket: https://github.com/orgs/openedx/projects/55/views/1?pane=issue&itemId=41364695

chore: remove xblock-utils

---

requirements/base.txt
requirements/ci.txt
requirements/dev.in
requirements/dev.txt
requirements/doc.txt
requirements/pip-tools.txt
requirements/pip.txt
requirements/quality.txt
requirements/test.txt

tox-battery is preventing us from upgrading tox.  It only did one thing, and tox 4 now does that automatically.

Remove tox-battery

---

scripts/repo-health-artifact.sh
scripts/repo-health-script.sh

- PR created under the issue https://github.com/openedx/edx-repo-health/issues/405
- This PR modifies the `repo-health-job` script to skip generating the sqlite3 db file which was previously being committed to the repository.
- After this change, a new script `repo-health-artifact` gets triggered to generate sqlite3 db file separately from the yaml files committed to the repository by the `repo health workflow build`. 
- The new script has been tested to work successfully in a test build https://github.com/edx/repo-health-data/actions/runs/7085336098
- The sqlite3 db file is being successfully generated as artifact with the job.

build: extract sqldb generation in repo health job as artifact

---

repo_health/utils.py

toml.load function read toml file and converts into dict, it take both content and file path and decides. But In our case we were passing file content but due to some reasons in the content it was considering it a file so now we are reading it using file name so that load function always use path to read file, I tested it on local.
Error build: https://github.com/edx/repo-health-data/actions/runs/7298483488/job/19889543897#step:10:783

Read toml using path not file content

---

repo_health/check_python_support_releases.py
repo_health/check_setup_py.py
repo_health/utils.py
repo_health_dashboard/dependencies_configuration.yaml
repo_health_dashboard/repo_health_dashboard.py
scripts/dependencies-health-script.sh

- PR created under the issue https://github.com/edx/edx-arch-experiments/issues/231
- Added new dependencies_health script to create new dependencies dashboard with scheduled workflow.

build: add dependencies health script

---

requirements/constraints.txt
requirements/pip.txt

`setuptools` update from `v69` to `v70` broke the `repo-health-workflow`. The link to the broken workflow is [mentioned here](https://github.com/edx/repo-health-data/actions/runs/10846619044/job/30103106806). This PR downgrades the setuptools so workflow can be successful. 
Issue to resolve issue regarding the setuptools upgrade: https://github.com/openedx/edx-repo-health/issues/523

fix: downgraded the setuptools to v70

---

catalog-info.yaml

- As per the discussion in Maintenance working group, `arbi-bom` team will maintain this repo from now on.

docs: add arbi-bom team as maintainer

---

.github/workflows/ci.yml

- Bumping the version of `actions/checkout@v4`

chore: bump checkout version

---

.github/workflows/ci.yml
CHANGELOG.rst
repo_health/__init__.py
requirements/base.txt
requirements/ci.txt
requirements/dev.txt
requirements/doc.txt
requirements/pip-tools.txt
requirements/pip.txt
requirements/quality.txt
requirements/test.txt
setup.py

- resolves: https://github.com/openedx/edx-repo-health/issues/521
---
- drop support for python versions older than 3.11
- upgrade requirements

Add support for python 3.11 and 3.12 | Drop support for python 3.8
