openedx/edx-repo-health

repo_health/check_makefile.py
repo_health/check_openedx_yaml.py
repo_health/check_requirements.py
repo_health/check_tox_ini.py
repo_health_dashboard/csv_dashboard.py

Added metadata to checks using the two decorator methods that come with pytest-repo-health

Added metadata to checks

---

repo_health/check_existence.py
repo_health/check_makefile.py

I'm a bit stumped on some of the doc strings for the checks, if you can help, that would be amazing! @timmc-edx

Adding checks for existence for files/dirs

---

repo_health/check_travis_yml.py
repo_health_dashboard/configuration.yaml

Check if python 3.8 is in .travis.yml. 
This sets as true or false travis_yml.py38_tests as true if there are tests with python 3.8

[BD-6] Python 3.8 in travis

---

repo_health/check_setup_py.py

Check if python 3.8 is in setup.py classifiers.
This sets as true or false setup_py.py38_classifiers as true if there are python 3.8 classifiers in setup.py

[BD-6] Python 3.8 is in classifiers

---

.travis.yml
openedx.yaml
setup.py
tox.ini

Remove python 3.6 and python 3.7 from tests.
**Reviewers**

[BD-6] Remove unsupported python versions.

---

repo_health/check_makefile.py

Added makefile checks(quality, quality-js, quality-python, test, test-js, test-python) as described in [BD-18]

[BD-18] Added makefile checks

---

repo_health/check_tox_ini.py

https://openedx.atlassian.net/browse/BOM-1954
Check for tox whitelist_externals

Check for tox whitelist_externals

---

repo_health/check_existence.py
repo_health/check_makefile.py

Refacatored file existence checks and added ability to check existence of package.json

[BD-18] Refacatored file existence checks and added ability to check existence of package.json

---

repo_health/check_openedx_yaml.py

Relevant JIRA issue [here](https://openedx.atlassian.net/browse/BOM-1974)

Added checks to identify and report any obsolete fields in openedx.yaml

---

repo_health/check_requirements.py

Relevant JIRA : https://openedx.atlassian.net/browse/BOM-1992

BOM-1992 : Check usage of boto

---

repo_health/check_openedx_yaml.py

See the recent change to OEP-2: https://github.com/edx/open-edx-proposals/pull/165

The nick key is obsolete in openedx.yaml

---

repo_health/check_github.py
repo_health/check_ownership.py

Relevant JIRA issue here: https://openedx.atlassian.net/browse/BOM-1981
this is the second PR to complete the requirement for this JIRA issue.
PRs
1. https://github.com/edx/pytest-repo-health/pull/49
2. current PR
3. https://github.com/edx/jenkins-job-dsl-internal/pull/432

Added logging to better report GitHub API failures

---

repo_health/check_github_integration.py
repo_health/check_travis_integration.py

https://openedx.atlassian.net/browse/BOM-2096
Checking github actions workflow integrated.
Workflows contains list and `ci.yml` can confirm tests are running.
```
"workflows": [
{
"id": 3670248,
"node_id": "MDg6V29ya2Zsb3czNjcwMjQ4",
"name": "CI",
"path": ".github/workflows/ci.yml",
"state": "active",
"created_at": "2020-11-17T15:48:18.000Z",
"updated_at": "2020-11-17T21:17:01.000Z",
"url": "https://api.github.com/repos/edx/course-discovery/actions/workflows/3670248",
"html_url": "https://github.com/edx/course-discovery/blob/master/.github/workflows/ci.yml",
"badge_url": "https://github.com/edx/course-discovery/workflows/CI/badge.svg"
},
```

Checking github actions workflow integrated.

---

repo_health/check_github_integration.py

Fixing a bug related with workflow key

---

repo_health/check_github_integration.py

Reverts edx/edx-repo-health#85

Revert "Fixing a bug related with workflow key"

---

repo_health/check_github_integration.py
repo_health/check_travis_integration.py

https://openedx.atlassian.net/browse/BOM-2096
Checking github actions workflow integrated.
Workflows contains list and `ci.yml` can confirm tests are running.
```
"workflows": [
{
"id": 3670248,
"node_id": "MDg6V29ya2Zsb3czNjcwMjQ4",
"name": "CI",
"path": ".github/workflows/ci.yml",
"state": "active",
"created_at": "2020-11-17T15:48:18.000Z",
"updated_at": "2020-11-17T21:17:01.000Z",
"url": "https://api.github.com/repos/edx/course-discovery/actions/workflows/3670248",
"html_url": "https://github.com/edx/course-discovery/blob/master/.github/workflows/ci.yml",
"badge_url": "https://github.com/edx/course-discovery/workflows/CI/badge.svg"
},
```

Checking github integration enable.

---

repo_health/check_github_integration.py

Adding some logs to check github response

Adding some logs to check github response

---

repo_health/check_github_integration.py

Adding authentication in request.

Fixing ratelimit.

---

repo_health/check_branches_and_pulls.py

Relevant JIRA : https://openedx.atlassian.net/browse/BOM-2084

BOM-2084 : Add repo health checks for branch and open PR counts

---

repo_health/check_readme.py

This checks for mentions of community resources in the README file. Some are good references and should be there, some are obsolete references and should no longer be there.

feat: Added checks of some community references in README.rst

---

pylintrc
requirements/base.txt
requirements/ci.txt
requirements/constraints.txt
requirements/dev.txt
requirements/doc.txt
requirements/pip.txt
requirements/quality.txt
requirements/test.txt

**Jira Issue:** [BOM-2272](https://openedx.atlassian.net/browse/BOM-2272)

Pin diff-cover<4.2.0

---

repo_health/check_readme.py

Bad things are True if they are missing (so that everything should be
True), so their descriptions were backwards.

fix: descriptions of bad things were reversed

---

README.rst
scripts/run_checks.py

Question for reviewer: does this change make the script too free/add complexity. I'm not completely sold on whether this needs to be a thing.

feat: Pass additional flags to pytest call

---

repo_health/check_github.py
repo_health/queries.py
repo_health/utils.py
tests/graphql_responses/ci_duration_response_empty.json
tests/graphql_responses/ci_duration_response_multiple_runs.json
tests/graphql_responses/ci_duration_response_multiple_suits.json
tests/graphql_responses/ci_duration_response_single.json
tests/test_ci_duration_check.py

Relevant JIRA : https://openedx.atlassian.net/browse/BOM-2343

BOM-2343 : Add health check for CI duration

---

repo_health/utils.py
tests/graphql_responses/ci_duration_response_in_progress.json
tests/test_ci_duration_check.py

Relevant JIRA : https://openedx.atlassian.net/browse/BOM-2454

BOM-2454 : Fix Build Duration Check Error in Health Dashboard

---

repo_health/utils.py
tests/test_ci_duration_check.py

Relevant JIRA : https://openedx.atlassian.net/browse/BOM-2449

BOM-2494: Sort build checks by duration

---

.github/workflows/upgrade-python-requirements.yml

Add a Github action to run the automated python requirements upgrade job using Github Actions.

build: Add python requirements upgrade action

---

.github/workflows/upgrade-python-requirements.yml

JIRA: https://openedx.atlassian.net/browse/BOM-2462

build: update commit msg in upgrade-python-requirements workflow

---

.github/workflows/upgrade-python-requirements.yml

JIRA: https://openedx.atlassian.net/browse/BOM-2462

Updated PR title in upgrade-python-requirements workflow

---

repo_health/check_readme.py
tests/test_check_readme.py

Using a dict was making a column in the spreadsheet for each key.  Now it's a list.

fix: correct the readme.bad_links reported data

---

repo_health/check_setup_py.py
tests/fake_repos/README.rst
tests/fake_repos/docs_repo/README.md
tests/fake_repos/just_setup_cfg/setup.cfg
tests/fake_repos/just_setup_cfg/setup.py
tests/fake_repos/just_setup_py/setup.py
tests/fake_repos/kodegail/setup.cfg
tests/fake_repos/kodegail/setup.py
tests/test_check_setup_py.py

This looks in the setup.py or setup.cfg file to find the name of the PyPI package the repo provides.

feat: extract the PyPI package name

---

repo_health/check_github_integration.py
repo_health_dashboard/repo_health_dashboard.py

appending org name in repo name column
BOM-2478

refactor: appending org name in repo name column.

---

repo_health/check_dependencies.py
repo_health/check_github.py

Reverts edx/edx-repo-health#143

Revert "refactor: converting dependencies list into json."

---

repo_health/check_github_integration.py
repo_health_dashboard/repo_health_dashboard.py

Reverts edx/edx-repo-health#145

Revert "refactor: appending org name in repo name column."

---

repo_health/check_dependencies.py
repo_health/check_github.py
repo_health/check_github_integration.py
repo_health_dashboard/repo_health_dashboard.py

Adding dependencies as json.
Appending org name in repo name column.
Out put.
```
'{"count": 62, "list": ["six==1.15.0", "websocket-client==0.58.0", "readme-renderer==29.0",
"babel==2.9.0", "docker-compose==1.29.0", "imagesize==1.2.0", "distlib==0.3.1",
"idna==2.10", "texttable==1.6.3", "alabaster==0.7.12", "pygments==2.8.1",
"bcrypt==3.2.0", "cryptography==3.4.7", "tox-battery==0.6.1", "bleach==3.3.0"]}
```
BOM-2478

refactor: appending org name in repo name column and adding dependencies as json.

---

CHANGELOG.rst
repo_health/__init__.py
repo_health/check_dependencies.py
tests/test_check_dependencies.py

refactor: Adding testing dependencies.
BOM-2478

refactor: Adding testing dependencies.

---

CHANGELOG.rst
repo_health/__init__.py
repo_health/check_dependencies.py
tests/test_check_dependencies.py

Few repos don't have base or production.txt. Fixing these edge cases.

Few repos don't have base or production.txt. Fixing these edge cases.

---

CHANGELOG.rst
repo_health/__init__.py
repo_health/check_npm_package.py
tests/fake_repos/js_repo/package.json
tests/fake_repos/python_js_repo/package.json
tests/test_npm_package_name.py

Added: Adding npm published package names.
https://openedx.atlassian.net/browse/BOM-2498

Added: Adding npm published package names.

---

CHANGELOG.rst
repo_health/check_dependencies.py
setup.py
tests/fake_repos/js_repo/package-lock.json
tests/fake_repos/python_js_repo/package-lock.json
tests/test_check_dependencies.py

Relevant JIRA : https://openedx.atlassian.net/browse/BOM-2538

BOM-2538: Repo health check for all JS dependencies

---

tests/test_check_existence.py

JIRA: https://openedx.atlassian.net/browse/BOM-2552

test: Added tests for check_existence

---

.github/workflows/ci.yml
.gitignore
codecov.yml
requirements/base.txt
requirements/ci.txt
requirements/dev.txt
requirements/doc.txt
requirements/pip-tools.txt
requirements/pip.txt
requirements/quality.txt
requirements/test.in
requirements/test.txt
tox.ini

Relevant JIRA : https://openedx.atlassian.net/browse/BOM-2554

BOM-2554: Add code coverage

---

repo_health/check_existence.py
tests/test_check_existence.py

Relevant JIRA : https://openedx.atlassian.net/browse/BOM-2144

BOM-2144: Update README check to support both RST and MD extensions

---

repo_health/check_ubuntufiles.py

chore: Removed unwanted characters from docker file parsing.
BOM-2537

chore: Removed unwanted characters from dockerfile parsing.

---

repo_health/check_docs.py

Previously Read the Docs checks were giving inconvenient output, so updating that. Now last_build_status, last_build_time and last_good_build_time is added into single dict identified by the project name.
Also converted output format from python dict object to json array.
[BOM-2540](https://openedx.atlassian.net/browse/BOM-2540)

refactor: update output of readthedocs checks

---

tests/fake_repos/openedx_repo1/openedx.yaml
tests/fake_repos/openedx_repo2/openedx.yaml
tests/test_check_openedx_yaml.py

JIRA: https://openedx.atlassian.net/browse/BOM-2571

test: Added tests for openedx_yaml check

---

repo_health/check_travis_yml.py
tests/fake_repos/travis_repo1/.travis.yml
tests/fake_repos/travis_repo2/.travis.yml
tests/test_check_travis_yml.py

JIRA: https://openedx.atlassian.net/browse/BOM-2569

test: Added tests for travis_yml check and made a correction in check

---

tests/fake_repos/tox_repo1/tox.ini
tests/fake_repos/tox_repo2/tox.ini
tests/test_check_tox_ini.py

JIRA: https://openedx.atlassian.net/browse/BOM-2574

test: Added tests for tox.ini check

---

tests/data/readthedocs_builds_failure.json
tests/data/readthedocs_builds_success.json
tests/data/readthedocs_projects.json
tests/fake_repos/no_read_the_docs/.readthedocs.yml
tests/fake_repos/no_read_the_docs/README.rst
tests/fake_repos/read_the_docs/.readthedocs.yml
tests/fake_repos/read_the_docs/README.rst
tests/test_check_docs.py

JIRA: https://openedx.atlassian.net/browse/BOM-2566

test: Added tests for docs check

---

tests/fake_repos/renovate_repo1/renovate.json
tests/test_check_renovate.py

JIRA: https://openedx.atlassian.net/browse/BOM-2573

test: Added tests for renovate check

---

repo_health/check_ownership.py
tests/data/ownership_data.csv
tests/test_check_ownership.py

JIRA: https://openedx.atlassian.net/browse/BOM-2572

test: Added tests for ownership check

---

.github/workflows/ci.yml
repo_health/check_github_integration.py
tests/data/github_integrated.json
tests/data/github_not_integrated.json
tests/test_check_github_integration.py

JIRA: https://openedx.atlassian.net/browse/BOM-2570

test: Added tests for github_integration check

---

repo_health/check_travis_yml.py
tests/fake_repos/travis_repo1/.travis.yml
tests/fake_repos/travis_repo2/.travis.yml
tests/test_check_travis_yml.py

JIRA: https://openedx.atlassian.net/browse/BOM-2569

test: Added tests for travis_yml check

---

requirements/base.txt
requirements/ci.txt
requirements/constraints.txt
requirements/dev.txt
requirements/doc.txt
requirements/quality.txt
requirements/test.txt

Removed constraints which are not needed anymore and are causing conflicts in upgrading requirements with `make upgrade` job causing that to [fail](https://github.com/openedx/edx-repo-health/runs/4890172088?check_suite_focus=true).

Remove unnecessary constraints

---

.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.rst

* Updates changelog with recent past changes.
* Adds PR template to remind about changelog.

fix: Update changelog

---

repo_health/check_ownership.py

Need to add expected_headers to fix backward incompatibility.

fix: fix upgrade to gspread

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt
requirements/doc.txt
requirements/pip-tools.txt
requirements/pip.txt
requirements/quality.txt
requirements/test.txt

- Fixed the upgrade job by running the job locally since the automated GitHub action fails due to pip version conflict installed within the environment.

fix: fix upgrade job pip failure

---

Makefile
tox.ini

https://2u-internal.atlassian.net/browse/BOM-2139

chore: Fixing tox for running locally. It was not collecting any tests.

---

repo_health/check_makefile.py

Updated the check to handle the following:
1. Upgrade script is last target in Makefile
2. There isn't any space after next target

fix: Fixed the upgrade_script check

---

.github/workflows/upgrade-python-requirements.yml

fix: upgrade job was failing due to broken link.

---

.github/workflows/automerge.yml

Adding github action for `automerge`. This is prototype work.

build: Adding automerge github actions functionality.

---

.github/dependabot.yml

The tests/fake_repos directory has dependencies, but they should be static, not changed.

build: focus dependabot on what it should update

---

repo_health/__init__.py
repo_health/check_django_dependencies_compatibility.py
repo_health/check_github.py
repo_health/check_github_integration.py
repo_health/check_openedx_yaml.py
repo_health/check_ownership.py
repo_health/check_travis_integration.py
repo_health/check_ubuntufiles.py
repo_health/utils.py

Code clean-ups

---

CHANGELOG.rst
repo_health_dashboard/repo_health_dashboard.py

Read yaml files for both orgs while creating dashboard

feat: read yaml files for both orgs

---

CHANGELOG.rst
repo_health/__init__.py
repo_health_dashboard/repo_health_dashboard.py
repo_health_dashboard/utils/utils.py

Add sqlite output

---

repo_health/check_docs.py
repo_health/check_travis_yml.py
requirements/github.in
tests/test_check_dependencies.py
tests/test_check_django_deps.py
tests/test_check_docs.py
tests/test_check_existence.py
tests/test_check_github_integration.py
tests/test_check_makefile.py
tests/test_check_openedx_yaml.py
tests/test_check_ownership.py
tests/test_check_readme.py
tests/test_check_renovate.py
tests/test_check_requirements.py
tests/test_check_setup_py.py
tests/test_check_tox_ini.py
tests/test_check_travis_yml.py
tests/test_check_ubuntufiles.py
tests/test_ci_duration_check.py
tests/test_npm_package_name.py
tests/test_travis_integration.py
tests/test_ubuntu_dependencies.py
tox.ini

- Add quality coverage to tests directory (and fix lint issues there)
- Prevent virtualenv from being checked, if it's in the working directory
Also:
- Add issue link to github.in entry
- Fix typo in check name (check_build_badge)
- Rename Travis fixture defs to match their registered names (easier to check imports that way)

test: Run quality checks on all (and only) repo directories

---

requirements/base.txt
requirements/dev.txt
requirements/doc.txt
requirements/quality.txt
requirements/test.txt

Reverts openedx/edx-repo-health#369

Revert "Python Requirements Update"

---

CHANGELOG.rst
repo_health/check_dependabot.py
tests/fake_repos/dependabot_exists_repo/.github/dependabot.yml
tests/test_check_dependabot.py

fix: new check file added for dependabot configs

---

CHANGELOG.rst
repo_health/__init__.py
repo_health_dashboard/console_dashboard_config.yaml
repo_health_dashboard/utils/utils.py
requirements/dev.in
requirements/dev.txt
scripts/console_dashboard.py
scripts/streamlit_dashboard.py

Some experiments in custom dashboard creation from a hackathon project:
* A script to generate a console report of actionable tasks, including context for prioritization, optionally filtered by one or more squads
* A script to view the main SQLite data table in a browser via streamlit and ag-grid.
I also fixed a bug where the string "None" was being inserted into the SQLite file for missing values, wherease they should have been NULL instead.

feat: Added console and streamlit dashboards, fixed SQLite empty values

---

repo_health/check_ownership.py
repo_health_dashboard/repo_health_dashboard.py
scripts/repo-health-script.sh
tests/test_check_ownership.py

Updating the repo health workflow script to work perfectly in all use cases with both GitHub Actions & Jenkins Job.
- Tested the script by triggering a successful custom workflow [build](https://github.com/edx/repo-health-data/actions/runs/5612140854/job/15205217936). 
- The updated yaml files were successfully merged in the `repo-health-data` repository in the [commit](https://github.com/edx/repo-health-data/commit/cd2e0760db76146b3c912c88b57d91163f05f42c). 
- Data Processing for sqlite db is failing currently which will be fixed in a follow up issue.
- Till then, the sqlite db copy won't be updated.
- The Jenkins job compatibility code will be removed once the Jenkins job has been removed.

Update repo health script

---

repo_health/check_renovate.py

Currently, the renovate `Last PR` check is not working properly for the openedx repos. This  PR fixes the issue related to the renovate check.

fix: renovate check last pr issue

---

tests/fake_repos/js_repo/package.json
tests/fake_repos/python_js_repo/package.json

I didn't update the package-lock.json because it looks like that is not
generated from this file in the test repos to begin with.

test: Update fake package.json to reduce confusion.

---

repo_health_dashboard/repo_health_dashboard.py
scripts/repo-health-script.sh

- Fixed the repo health workflow dbsqlite issue
- Tested the workflow by triggering a custom workflow with the changes in this branch. 
- A follow up PR will be created to also export the generated db file as workflow artifact file.

fix: fix repo health sqlite db issue
